# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1092, 846)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(70, 90, 981, 641))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 979, 639))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.scrollAreaWidgetContents)
        self.verticalScrollBar.setGeometry(QtCore.QRect(960, 0, 20, 641))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.tableView = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tableView.setGeometry(QtCore.QRect(0, 0, 961, 641))
        self.tableView.setObjectName("tableView")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.header = QtWidgets.QLabel(self.centralwidget)
        self.header.setGeometry(QtCore.QRect(400, 30, 301, 51))
        self.header.setTextFormat(QtCore.Qt.PlainText)
        self.header.setScaledContents(False)
        self.header.setAlignment(QtCore.Qt.AlignCenter)
        self.header.setObjectName("header")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1092, 21))
        self.menubar.setObjectName("menubar")
        self.menuSports = QtWidgets.QMenu(self.menubar)
        self.menuSports.setObjectName("menuSports")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNFL = QtWidgets.QAction(MainWindow)
        self.actionNFL.setObjectName("actionNFL")
        self.actionNBA = QtWidgets.QAction(MainWindow)
        self.actionNBA.setObjectName("actionNBA")
        self.actionNCAA_Football = QtWidgets.QAction(MainWindow)
        self.actionNCAA_Football.setObjectName("actionNCAA_Football")
        self.actionPremiere_League = QtWidgets.QAction(MainWindow)
        self.actionPremiere_League.setObjectName("actionPremiere_League")
        self.actionMLB = QtWidgets.QAction(MainWindow)
        self.actionMLB.setObjectName("actionMLB")
        self.actionChampions_League = QtWidgets.QAction(MainWindow)
        self.actionChampions_League.setObjectName("actionChampions_League")
        self.menuSports.addAction(self.actionNFL)
        self.menuSports.addAction(self.actionNBA)
        self.menuSports.addAction(self.actionNCAA_Football)
        self.menuSports.addAction(self.actionPremiere_League)
        self.menuSports.addAction(self.actionMLB)
        self.menuSports.addAction(self.actionChampions_League)
        self.menubar.addAction(self.menuSports.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.header.setText(_translate("MainWindow", "This Weeks Games"))
        self.menuSports.setTitle(_translate("MainWindow", "Sports"))
        self.actionNFL.setText(_translate("MainWindow", "NFL"))
        self.actionNBA.setText(_translate("MainWindow", "NBA"))
        self.actionNCAA_Football.setText(_translate("MainWindow", "NCAA Football"))
        self.actionPremiere_League.setText(_translate("MainWindow", "Premiere League"))
        self.actionMLB.setText(_translate("MainWindow", "MLB"))
        self.actionChampions_League.setText(_translate("MainWindow", "Champions League"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
